version: "3.8"

services:
  redis:
    image: redis:7.2.5
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  redis-data:
    name: redis-data

